// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_chart from "./routes/[slug]/chart.tsx";
import * as $_slug_index from "./routes/[slug]/index.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cors_proxy_string_ from "./routes/api/cors-proxy/[...string].ts";
import * as $api_newData from "./routes/api/newData.ts";
import * as $index from "./routes/index.tsx";
import * as $lmn from "./routes/lmn.ts";
import * as $lậptrình from "./routes/lậptrình.ts";
import * as $ngụngôn from "./routes/ngụngôn.ts";
import * as $Biểu_đồ_echart from "./islands/Biểu đồ/echart.tsx";
import * as $Biểu_đồ_theme from "./islands/Biểu đồ/theme.tsx";
import * as $Khung_tìm_bài_đăng_hoặc_nơi_đăng from "./islands/Khung tìm bài đăng hoặc nơi đăng.tsx";
import * as $KhungKếtQuảBênPhải from "./islands/KhungKếtQuảBênPhải.tsx";
import * as $Kết_quả_được_chọn_Kết_quả_được_chọn from "./islands/Kết quả được chọn/Kết quả được chọn.tsx";
import * as $Kết_quả_được_chọn_Nơi_đăng_được_chọn from "./islands/Kết quả được chọn/Nơi đăng được chọn.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $Modal_tạo_mới_Modal_bài_đăng from "./islands/Modal tạo mới/Modal bài đăng.tsx";
import * as $Modal_tạo_mới_Modal_chung from "./islands/Modal tạo mới/Modal chung.tsx";
import * as $Modal_tạo_mới_Modal_nơi_đăng from "./islands/Modal tạo mới/Modal nơi đăng.tsx";
import * as $Section_bên_trái from "./islands/Section bên trái.tsx";
import * as $Signals from "./islands/Signals.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug]/chart.tsx": $_slug_chart,
    "./routes/[slug]/index.ts": $_slug_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/cors-proxy/[...string].ts": $api_cors_proxy_string_,
    "./routes/api/newData.ts": $api_newData,
    "./routes/index.tsx": $index,
    "./routes/lmn.ts": $lmn,
    "./routes/lậptrình.ts": $lậptrình,
    "./routes/ngụngôn.ts": $ngụngôn,
  },
  islands: {
    "./islands/Biểu đồ/echart.tsx": $Biểu_đồ_echart,
    "./islands/Biểu đồ/theme.tsx": $Biểu_đồ_theme,
    "./islands/Khung tìm bài đăng hoặc nơi đăng.tsx":
      $Khung_tìm_bài_đăng_hoặc_nơi_đăng,
    "./islands/KhungKếtQuảBênPhải.tsx": $KhungKếtQuảBênPhải,
    "./islands/Kết quả được chọn/Kết quả được chọn.tsx":
      $Kết_quả_được_chọn_Kết_quả_được_chọn,
    "./islands/Kết quả được chọn/Nơi đăng được chọn.tsx":
      $Kết_quả_được_chọn_Nơi_đăng_được_chọn,
    "./islands/Main.tsx": $Main,
    "./islands/Modal tạo mới/Modal bài đăng.tsx": $Modal_tạo_mới_Modal_bài_đăng,
    "./islands/Modal tạo mới/Modal chung.tsx": $Modal_tạo_mới_Modal_chung,
    "./islands/Modal tạo mới/Modal nơi đăng.tsx": $Modal_tạo_mới_Modal_nơi_đăng,
    "./islands/Section bên trái.tsx": $Section_bên_trái,
    "./islands/Signals.ts": $Signals,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
