// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.ts";
import * as $lmn from "./routes/lmn.ts";
import * as $lậptrình from "./routes/lậptrình.ts";
import * as $ngụngôn from "./routes/ngụngôn.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].ts": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.ts": $index,
    "./routes/lmn.ts": $lmn,
    "./routes/lậptrình.ts": $lậptrình,
    "./routes/ngụngôn.ts": $ngụngôn,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
