// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_chart from "./routes/[slug]/chart.tsx";
import * as $_slug_index from "./routes/[slug]/index.ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cors_proxy_url_ from "./routes/api/cors-proxy/[...url].ts";
import * as $api_newData from "./routes/api/newData.ts";
import * as $index from "./routes/index.tsx";
import * as $lmn from "./routes/lmn.ts";
import * as $lậptrình from "./routes/lậptrình.ts";
import * as $ngụngôn from "./routes/ngụngôn.ts";
import * as $Khung_tìm_bài_đăng_hoặc_nơi_đăng from "./islands/Khung tìm bài đăng hoặc nơi đăng.tsx";
import * as $KhungKếtQuảBênPhải from "./islands/KhungKếtQuảBênPhải.tsx";
import * as $KhungNhậpBênTrái from "./islands/KhungNhậpBênTrái.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $Modal_tạo_mới from "./islands/Modal tạo mới.tsx";
import * as $chart from "./islands/chart.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug]/chart.tsx": $_slug_chart,
    "./routes/[slug]/index.ts": $_slug_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/cors-proxy/[...url].ts": $api_cors_proxy_url_,
    "./routes/api/newData.ts": $api_newData,
    "./routes/index.tsx": $index,
    "./routes/lmn.ts": $lmn,
    "./routes/lậptrình.ts": $lậptrình,
    "./routes/ngụngôn.ts": $ngụngôn,
  },
  islands: {
    "./islands/Khung tìm bài đăng hoặc nơi đăng.tsx":
      $Khung_tìm_bài_đăng_hoặc_nơi_đăng,
    "./islands/KhungKếtQuảBênPhải.tsx": $KhungKếtQuảBênPhải,
    "./islands/KhungNhậpBênTrái.tsx": $KhungNhậpBênTrái,
    "./islands/Main.tsx": $Main,
    "./islands/Modal tạo mới.tsx": $Modal_tạo_mới,
    "./islands/chart.tsx": $chart,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
